#!/bin/sh
#create build directory under cie project root, cd into it and:
#mkdir -p build/install && cd build

export CMAKE_PREFIX_PATH=`pwd`/..
cmake -DCMAKE_INSTALL_PREFIX=`pwd`/../dist ..
make && make install/strip
find `pwd`/../dist/ -type d | xargs chmod 755
fakeroot dpkg-deb --build `pwd`/../dist
lintian `pwd`/../dist.deb
mv `pwd`/../dist.deb `pwd`/../libciepki1.0-1.deb
