#!/bin/sh
PROJ_ROOT = `pwd`
BUILD_DIR = $PROJ_ROOT/build

pushd $BUILD_DIR

cmake -DCMAKE_PREFIX_PATH=$PROJ_ROOT -DCMAKE_INSTALL_PREFIX=$PROJ_ROOT/dist $PROJ_ROOT
make && make install/strip
find $PROJ_ROOT/dist/ -type d | xargs chmod 755
fakeroot dpkg-deb --build $PROJ_ROOT/dist
lintian $PROJ_ROOT/dist.deb
mv $PROJ_ROOT/dist.deb $PROJ_ROOT/libciepki1.0-1.deb

popd
